export {
  PRODUCT_FILTER_VALID_VALUES,
  PRODUCT_STATUS_OPTIONS,
  PRODUCT_STATUS_LABELS,
  PRODUCT_FEATURED_OPTIONS,
  PRODUCT_IMAGE_OPTIONS,
  PRODUCT_VARIANT_OPTIONS,
  PRODUCT_STOCK_OPTIONS,
  PRODUCT_SORT_OPTIONS,
  // PRODUCT_LIST_PAGE_COPY,
  PRODUCT_LIST_COPY,
  PRODUCT_LIST_VIEW_OPTIONS,
  PRODUCT_LIST_ACTIONS_COPY,
  PRODUCT_SELECTION_COPY,
  PRODUCT_BULK_ACTIONS_COPY,
  PRODUCT_RESULTS_COUNT_COPY,
  PRODUCT_TABLE_COPY,
  PRODUCT_LIST_EMPTY_STATE_COPY,
  PRODUCT_STOCK_BADGE_COPY,
  PRODUCT_ROW_ACTIONS_COPY,
  PRODUCT_BULK_DELETE_DIALOG_COPY,
  PRODUCT_CARD_BADGES_COPY,
  PRODUCT_CARD_ACTIONS_COPY,
  PRODUCT_CARD_COPY,
} from "./product-list.config";

export { PRODUCT_LIFECYCLE_FEEDBACK_COPY } from "./product-feedback.config";
export { PRODUCT_SORTABLE_COLUMNS } from "./product-sortable.columns.config";

export {
  PRODUCT_EDITOR_NAV_COPY,
  PRODUCT_CREATE_PAGE_COPY,
  PRODUCT_CREATE_MENU_COPY,
  PRODUCT_EDITOR_PAGE_COPY,
  PRODUCT_EDITOR_MENUS_COPY,
  PRODUCT_FORM_ACTIONS_COPY,
  PRODUCT_CREATE_PANEL_COPY,
  PRODUCT_GENERAL_TAB_COPY,
  PRODUCT_PRICING_TAB_COPY,
  PRODUCT_AVAILABILITY_TAB_COPY,
  PRODUCT_INVENTORY_TAB_COPY,
  PRODUCT_CHARACTERISTICS_TAB_COPY,
  PRODUCT_RELATED_PRODUCTS_TAB_COPY,
  PRODUCT_CATEGORIES_TAB_COPY,
  PRODUCT_SEO_TAB_COPY,
  PRODUCT_IMAGES_TAB_COPY,
  PRODUCT_VARIANTS_TAB_COPY,
  PRODUCT_IMAGE_ITEM_COPY,
  PRODUCT_IMAGE_LIBRARY_COPY,
  PRODUCT_IMAGE_UPLOAD_COPY,
  PRODUCT_VARIANT_EDITOR_COPY,
  PRODUCT_VARIANT_ITEM_COPY,
  PRODUCT_VARIANT_IMAGE_PICKER_COPY,
} from "./product-editor.config";

// Navigation
export {
  PRODUCT_EDIT_PAGE_COPY,
  PRODUCT_LIST_PAGE_COPY,
  PRODUCT_NAVIGATION_COPY,
  PRODUCT_NEW_PAGE_COPY,
} from "./product-navigation.config";
