export const AUTOMATION_NEWSLETTER_SUBSCRIBED_JOB_TYPE = "AUTOMATION_NEWSLETTER_SUBSCRIBED";

export const AUTOMATION_NEWSLETTER_SUBSCRIBED_PAYLOAD_SCHEMA =
  "creatyss.automation.newsletter-subscribed-job.v1";

export const AUTOMATION_NEWSLETTER_SUBSCRIBER_SUBJECT_TYPE = "NEWSLETTER_SUBSCRIBER";

export const AUTOMATION_ORDER_PLACED_JOB_TYPE = "AUTOMATION_ORDER_PLACED";

export const AUTOMATION_ORDER_PLACED_PAYLOAD_SCHEMA = "creatyss.automation.order-placed-job.v1";

export const AUTOMATION_ORDER_SUBJECT_TYPE = "ORDER";

export const AUTOMATION_JOB_TYPE_CODES = [
  AUTOMATION_NEWSLETTER_SUBSCRIBED_JOB_TYPE,
  AUTOMATION_ORDER_PLACED_JOB_TYPE,
] as const;
