export const AUTOMATION_NEWSLETTER_SUBSCRIBED_JOB_TYPE =
  "AUTOMATION_NEWSLETTER_SUBSCRIBED";

export const AUTOMATION_NEWSLETTER_SUBSCRIBED_PAYLOAD_SCHEMA =
  "creatyss.automation.newsletter-subscribed-job.v1";

export const AUTOMATION_NEWSLETTER_SUBSCRIBER_SUBJECT_TYPE =
  "NEWSLETTER_SUBSCRIBER";
