import type { FeatureCatalogEntry } from "./feature-catalog.types";

export const FEATURE_LEVELS = {
  ai: ["basic", "assistant", "advanced", "automation"],
  analytics: ["read", "insights", "recommendations"],
  newsletter: ["basic", "segmentation", "automation"],
  media: ["basic", "optimization", "generation", "automation"],
  discounts: ["simple", "rules", "automation"],
  inventory: ["manual", "alerts", "forecasting"],
} as const;

export const FEATURE_CATALOG = [
  // Commerce — satellite modules
  {
    key: "commerce.fulfillment",
    label: "Traitement des commandes",
    description: "Gestion du cycle de traitement des commandes : préparation, expédition et suivi.",
    family: "satellite",
    module: "commerce",
    defaultState: "inactive",
    mutability: "toggleable",
    scopes: ["store"],
  },
  {
    key: "commerce.returns",
    label: "Retours",
    description: "Gestion des demandes de retour, remboursements et échanges.",
    family: "satellite",
    module: "commerce",
    defaultState: "inactive",
    mutability: "toggleable",
    scopes: ["store"],
  },
  {
    key: "commerce.documents",
    label: "Documents commerciaux",
    description: "Génération des factures, bons de commande et documents d'expédition.",
    family: "satellite",
    module: "commerce",
    defaultState: "inactive",
    mutability: "toggleable",
    scopes: ["store"],
  },
  {
    key: "commerce.taxation",
    label: "Fiscalité",
    description: "Gestion des règles de TVA, taxes locales et conformité fiscale.",
    family: "satellite",
    module: "commerce",
    defaultState: "inactive",
    mutability: "toggleable",
    scopes: ["store"],
  },
  {
    key: "commerce.payments",
    label: "Paiements",
    description: "Gestion des moyens de paiement et des transactions.",
    family: "satellite",
    module: "commerce",
    defaultState: "active",
    mutability: "toggleable",
    scopes: ["store"],
  },
  {
    key: "commerce.shipping",
    label: "Livraison",
    description: "Gestion des modes de livraison et des transporteurs.",
    family: "satellite",
    module: "commerce",
    defaultState: "active",
    mutability: "toggleable",
    scopes: ["store"],
  },
  {
    key: "commerce.discounts",
    label: "Remises",
    description: "Gestion des codes promo, règles de remise et promotions.",
    family: "satellite",
    module: "commerce",
    defaultState: "inactive",
    mutability: "level_selectable",
    scopes: ["store"],
    levels: FEATURE_LEVELS.discounts,
  },
  // Platform — optional modules
  {
    key: "platform.notifications",
    label: "Notifications",
    description: "Gestion des notifications email, SMS et push envoyées aux clients et à l'équipe.",
    family: "optional",
    module: "platform",
    defaultState: "inactive",
    mutability: "toggleable",
    scopes: ["store"],
  },
  {
    key: "platform.integrations",
    label: "Intégrations",
    description: "Connexions aux services tiers : ERP, CRM, outils marketing et plateformes externes.",
    family: "optional",
    module: "platform",
    defaultState: "inactive",
    mutability: "toggleable",
    scopes: ["store", "global"],
  },
  {
    key: "platform.webhooks",
    label: "Webhooks",
    description: "Émission d'événements vers des endpoints externes pour intégrations et automatisations.",
    family: "optional",
    module: "platform",
    defaultState: "inactive",
    mutability: "toggleable",
    scopes: ["store", "global"],
  },
  {
    key: "platform.localization",
    label: "Localisation",
    description: "Gestion des langues, devises et adaptations locales du contenu et des prix.",
    family: "optional",
    module: "platform",
    defaultState: "inactive",
    mutability: "toggleable",
    scopes: ["store"],
  },
  // Satellite — search and channels
  {
    key: "satellite.search",
    label: "Recherche avancée",
    description: "Moteur de recherche interne avec indexation, facettes et suggestions.",
    family: "satellite",
    module: "satellite",
    defaultState: "inactive",
    mutability: "toggleable",
    scopes: ["store"],
  },
  {
    key: "satellite.channels",
    label: "Canaux de vente",
    description: "Gestion des canaux de distribution : marketplaces, réseaux sociaux et points de vente.",
    family: "satellite",
    module: "satellite",
    defaultState: "inactive",
    mutability: "toggleable",
    scopes: ["store"],
  },
  // Engagement — optional modules
  {
    key: "engagement.newsletter",
    label: "Newsletter",
    description: "Gestion des campagnes email et des abonnements.",
    family: "optional",
    module: "engagement",
    defaultState: "inactive",
    mutability: "level_selectable",
    scopes: ["store"],
    levels: FEATURE_LEVELS.newsletter,
  },
  {
    key: "engagement.analytics",
    label: "Analytics",
    description: "Suivi des performances, des conversions et des audiences.",
    family: "optional",
    module: "engagement",
    defaultState: "inactive",
    mutability: "level_selectable",
    scopes: ["store"],
    levels: FEATURE_LEVELS.analytics,
  },
  // Catalog products — core capabilities
  {
    key: "catalog.products.pricing",
    label: "Tarification produit",
    description: "Gestion des prix, des taxes et des règles tarifaires.",
    family: "core",
    module: "catalog",
    capability: "catalog.products.pricing",
    defaultState: "active",
    mutability: "readonly",
    scopes: ["store"],
  },
  {
    key: "catalog.products.availability",
    label: "Disponibilité produit",
    description: "Gestion de la disponibilité et de la visibilité des produits.",
    family: "core",
    module: "catalog",
    capability: "catalog.products.availability",
    defaultState: "active",
    mutability: "readonly",
    scopes: ["store"],
  },
  {
    key: "catalog.products.inventory",
    label: "Inventaire produit",
    description: "Gestion du stock, des alertes et des prévisions d'inventaire.",
    family: "core",
    module: "catalog",
    capability: "catalog.products.inventory",
    defaultState: "active",
    mutability: "level_selectable",
    scopes: ["store"],
    levels: FEATURE_LEVELS.inventory,
  },
  {
    key: "catalog.products.media",
    label: "Médias produit",
    description: "Gestion des images, vidéos et contenus médias des produits.",
    family: "core",
    module: "catalog",
    capability: "catalog.products.media",
    defaultState: "active",
    mutability: "level_selectable",
    scopes: ["store"],
    levels: FEATURE_LEVELS.media,
  },
  {
    key: "catalog.products.variants",
    label: "Variantes produit",
    description: "Gestion des déclinaisons (taille, couleur, etc.).",
    family: "core",
    module: "catalog",
    capability: "catalog.products.variants",
    defaultState: "active",
    mutability: "readonly",
    scopes: ["store"],
  },
  {
    key: "catalog.products.seo",
    label: "SEO produit",
    description: "Gestion des métadonnées SEO et de l'optimisation pour les moteurs de recherche.",
    family: "core",
    module: "catalog",
    capability: "catalog.products.seo",
    defaultState: "active",
    mutability: "readonly",
    scopes: ["store"],
    dependencies: ["engagement.analytics"],
  },
  {
    key: "catalog.products.categories",
    label: "Catégories produit",
    description: "Organisation des produits en catégories et sous-catégories.",
    family: "core",
    module: "catalog",
    capability: "catalog.products.categories",
    defaultState: "active",
    mutability: "readonly",
    scopes: ["store"],
  },
  {
    key: "catalog.products.related",
    label: "Produits associés",
    description: "Gestion des suggestions de produits similaires ou complémentaires.",
    family: "core",
    module: "catalog",
    capability: "catalog.products.related",
    defaultState: "active",
    mutability: "toggleable",
    scopes: ["store"],
  },
  // Content — cross-cutting modules (structure éditoriale transverse)
  {
    key: "content.blog",
    label: "Blog",
    description: "Gestion des articles de blog et de la structure éditoriale.",
    family: "cross_cutting",
    module: "content",
    defaultState: "active",
    mutability: "readonly",
    scopes: ["store"],
  },
  {
    key: "content.homepage",
    label: "Page d'accueil",
    description: "Gestion du contenu et de la mise en page de la page d'accueil.",
    family: "cross_cutting",
    module: "content",
    defaultState: "active",
    mutability: "readonly",
    scopes: ["store"],
  },
  {
    key: "content.seo",
    label: "SEO global",
    description: "Gestion des métadonnées SEO et de l'optimisation transverse pour les moteurs de recherche.",
    family: "cross_cutting",
    module: "content",
    defaultState: "active",
    mutability: "readonly",
    scopes: ["store"],
  },
  // Settings — core pilotage
  {
    key: "settings.advanced",
    label: "Réglages avancés",
    description: "Pilotage des fonctionnalités, mutabilité et gouvernance des modules depuis l'admin.",
    family: "core",
    module: "settings",
    defaultState: "active",
    mutability: "readonly",
    scopes: ["store", "global"],
  },
  // Maintenance — cross-cutting observability
  {
    key: "maintenance.observability",
    label: "Observabilité",
    description: "Supervision transverse de l'état du système, des alertes et des indicateurs de santé.",
    family: "cross_cutting",
    module: "maintenance",
    defaultState: "active",
    mutability: "readonly",
    scopes: ["global"],
  },
  {
    key: "maintenance.logs",
    label: "Journaux système",
    description: "Accès aux journaux d'exploitation et aux traces d'audit.",
    family: "cross_cutting",
    module: "maintenance",
    defaultState: "active",
    mutability: "readonly",
    scopes: ["global"],
  },
  // Insights — capability de lecture analytics (distinct de engagement.analytics = module flag)
  // engagement.analytics = activation du module analytics par boutique
  // insights.analyticsRead = capability de lecture des données analytics dans l'admin
  {
    key: "insights.analyticsRead",
    label: "Lecture Analytics",
    description: "Capacité de lecture des données analytics dans l'interface d'administration.",
    family: "cross_cutting",
    module: "insights",
    capability: "insights.analyticsRead",
    defaultState: "active",
    mutability: "readonly",
    scopes: ["store", "global"],
    dependencies: ["engagement.analytics"],
  },
  // AI — optional module
  {
    key: "ai.core",
    label: "Intelligence artificielle",
    description: "Fonctionnalités IA transverses : génération de contenu, suggestions et automatisations.",
    family: "optional",
    module: "ai",
    defaultState: "inactive",
    mutability: "level_selectable",
    scopes: ["store"],
    levels: FEATURE_LEVELS.ai,
  },
] as const satisfies readonly FeatureCatalogEntry[];

export function getFeatureCatalogEntries(): readonly FeatureCatalogEntry[] {
  return FEATURE_CATALOG;
}

export function findFeatureCatalogEntry(key: string): FeatureCatalogEntry | null {
  return FEATURE_CATALOG.find((e) => e.key === key) ?? null;
}

export function isFeatureCatalogKey(key: string): boolean {
  return FEATURE_CATALOG.some((e) => e.key === key);
}
